import {createRouter,createWebHistory} from 'vue-router'

export default createRouter({
    history:createWebHistory(),
    routes:[
        {
            path:'/home',
            component:()=>import('@/pages/home/index.vue'),
            meta:{
                title:'首頁'
            }
        },
        {
            path:'/hospital',
            // redirect: '/hosptial/register',
            component:()=>import('@/pages/hospital/index.vue'),
            children:[
                {
                    path:'/hospital/register',
                    name: 'register',
                    component:()=>import('@/pages/hospital/register/index.vue'),
                    meta:{
                        title:'預約挂號'
                    }
                },
                {
                    path:'/hospital/detail',
                    name: 'detail',
                    component:()=>import('@/pages/hospital/detail/index.vue'),
                    meta:{
                        title:'醫院詳情'
                    }
                },
                {
                    path:'/hospital/notice',
                    name: 'notice',
                    component:()=>import('@/pages/hospital/notice/index.vue'),
                    meta:{
                        title:'預約通知'
                    }
                },
                {
                    path:'/hospital/close',
                    name: 'close',
                    component:()=>import('@/pages/hospital/close/index.vue'),
                    meta:{
                        title:'停診信息'
                    }
                },
                {
                    path:'/hospital/search',
                    name: 'search',
                    component:()=>import('@/pages/hospital/search/index.vue'),
                    meta:{
                        title:'查詢'
                    }
                },
                {
                    path:'/hospital/register_step1',
                    component:()=>import('@/pages/hospital/register/register_step1.vue'),
                    meta:{
                        title:'預約第一步'
                    }
                },
                {
                    path:'/hospital/register_step2',
                    component:()=>import('@/pages/hospital/register/register_step2.vue'),
                    meta:{
                        title:'預約第二步'
                    }
                }
            ]
        },
        {
            path:'/user',
            component:()=>import('@/pages/user/index.vue'),
            children:[
                {
                    path:'certification',
                    component:()=>import('@/pages/user/certification/index.vue'),
                    meta:{
                        title:'實名認證'
                    }
                },
                {
                    path:'order',
                    component:()=>import('@/pages/user/order/index.vue'),
                    meta:{
                        title:'挂號訂單'
                    }
                },
                {
                    path:'patient',
                    component:()=>import('@/pages/user/patient/index.vue'),
                    meta:{
                        title:'就診人管理'
                    }
                },
                {
                    path:'profile',
                    component:()=>import('@/pages/user/profile/index.vue'),
                    meta:{
                        title:'賬號信息'
                    }
                },
                {
                    path:'feedback',
                    component:()=>import('@/pages/user/feedback/index.vue'),
                    meta:{
                        title:'意見反饋'
                    }
                }
            ]
        },
        {
            path:'/',
            redirect:'/home'
        }
    ],
    //滾動行爲
    scrollBehavior(){
        return{
            left:0,
            top:0
        }
    }
})